Created DELETE and PUT endpoints
NCATS-Gamma/robokache pull request #10
Opened 2020-09-09 21:01 UTC by alongreyber

Created DELETE and PUT endpoints for both Questions and Answers.

Updates to the API specification are not included in this pull request. There is a large refactoring to the API specification coming soon so it doesn't make sense to make those changes right now.

2020-09-10 00:43 UTC, patrickkwang requested changes
Two big oddities:
1. DeleteQuestion does not take the userEmail like all of the other similar methods do. You put it in the Question object instead. I think that what you've done works, but line 21 there may be unreachable because GetQuestion will fail first. We should make this consistent with everything else. Passing userEmail around everywhere feels janky, so a more elegant solution might be nice.
2. Deleting answers should not require the corresponding question ID. Maybe we just call GetAnswer instead of GetQuestion in DeleteAnswer, or maybe we just have to get more clever with the SQL.

2020-09-10 00:43 UTC, patrickkwang commented on internal/robokache/delete.go
> +		return errors.New("Unauthorized: You do not own this question and may not add answers")
```suggestion
		return errors.New("Unauthorized: You do not own this answer")
```

2020-09-10 00:43 UTC, patrickkwang commented on internal/robokache/delete.go
> +		return errors.New("Unauthorized: You do not own this question and may not add answers")
```suggestion
		return errors.New("Unauthorized: You do not own this question")
```

2020-09-10 00:43 UTC, patrickkwang commented on internal/robokache/main_test.go
> +	w = performRequest(router, "GET", "/api/answers/0", signedString, nil)
```suggestion
	w = performRequest(router, "GET", "/api/answers/0a", signedString, nil)
```

2020-09-14 19:23 UTC, alongreyber commented
These changes have been added to #16.

2020-09-14 19:23 UTC, closed without merging